#' Extract mutational signatures from trinucletide context.
#'
#' @description Decompose a matrix of 96 substitution classes into \code{n} signatures.
#'
#' @details This function decomposes a non-negative matrix into n signatures.
#' Extracted signatures are compared against 21 experimentally validated signatures by calculating correlation coefficient. See http://www.nature.com/nature/journal/v500/n7463/fig_tab/nature12477_F2.html for details.
#'
#' @param mat Input matrix of diemnsion nx96 generated by \code{\link{trinucleotideMatrix}}
#' @param n decompose matrix into n signatures. Default NULL. Tries to predict best value for \code{n} by running NMF on a range of values and chooses the one with highest cophenetic correlation coefficient.
#' @param nTry tries upto this number of signatures before choosing best \code{n}. Default 6.
#' @return returns a list with decomposed signatures and correlatoon table against validated signatures.
#' @export


extractSignatures = function(mat, n = NULL, nTry = 6){

  require(NMF, quietly = T)
  #transpose matrix
  mat = t(mat)

  #Validation
  zeroMutClass = names(which(rowSums(mat) == 0))

  if(length(zeroMutClass)){
    message(paste('Warning : Found zero mutations for conversions ', zeroMutClass, sep=''))
    #Add small value to avoid zero counts (maybe not appropriate). This happens when sample size is low or in cancers with low mutation rate.
    mat[which(rowSums(mat) == 0),] = 0.1
  }

  #Notes:
  #Available methods for nmf decompositions are 'brunet', 'lee', 'ls-nmf', 'nsNMF', 'offset'.
  #But based 21 breast cancer signatures data, defualt brunet seems to be working close to the results.
  #Sticking with default for now.

  if(is.null(n)){
    message('Estimating best rank..')
    nmfTry = NMF::nmfEstimateRank(mat, seq(2,nTry), method='brunet', nrun=10, seed=123456) #try nmf for a range of values
    print(plot(nmfTry, 'cophenetic' ))
    nmf.sum = summary(nmfTry) # Get summary of estimates
    print(nmf.sum)
    bestFit = nmf.sum[which(nmf.sum$cophenetic == max(nmf.sum$cophenetic)),'rank'] #Get the best rank based on highest cophenetic correlation coefficient
    message(paste('Using ',bestFit, ' as a best-fit rank based on maximum cophenetic correlation coefficient.', sep=''))
    n = bestFit
  }

  conv.mat.nmf = NMF::nmf(x = mat, rank = n)

  conv.mat.nmf.signatures = basis(conv.mat.nmf)
  conv.mat.nmf.signatures = apply(conv.mat.nmf.signatures, 2, function(x) x/sum(x)) #Scale the signatures

  colnames(conv.mat.nmf.signatures) = paste('Signature', 1:ncol(conv.mat.nmf.signatures),sep='_')
  #conv.mat.nmf.signatures.melted = melt(conv.mat.nmf.signatures)
  #levels(conv.mat.nmf.signatures.melted$X1) = colOrder

  sigs = fread(input = system.file('extdata', 'signatures.txt', package = 'maftools'), stringsAsFactors = F, data.table = F)
  colnames(sigs) = gsub(pattern = ' ', replacement = '_', x = colnames(sigs))
  rownames(sigs) = sigs$Somatic_Mutation_Type
  sigs = sigs[,-c(1:3)]
  sigs = sigs[,1:22] #use only first 21 validated sigantures
  sigs = sigs[rownames(conv.mat.nmf.signatures),]

  message('Comparing against experimentally validated 21 signatures.. (See Alexandrov et.al Nature 2013 for details.)')
  corMat = c()
  for(i in 1:ncol(conv.mat.nmf.signatures)){
    sig = conv.mat.nmf.signatures[,i]
    corMat = rbind(corMat, apply(sigs, 2, function(x) cor.test(x, sig)$estimate[[1]])) #Calulate correlation coeff.
  }
  rownames(corMat) = colnames(conv.mat.nmf.signatures)

  for(i in 1:nrow(corMat)){
    message('Found ',rownames(corMat)[i], ' most similar to validated ',names(which(corMat[i,] == max(corMat[i,]))), '. Correlation coeff: ', max(corMat[i,]), sep=' ')
  }

  return(list(signatures = conv.mat.nmf.signatures, corTable = corMat))
}
