#' Clusters variants based on Variant Allele Frequencies (VAF).
#' @description takes output generated by read.maf and clusters variants to infer tumor heterogenity (multiple clones).
#'
#' @details This function clusters variants in a particlar tumor sample by running \code{densityMclust} on vaf's to estimate univariate density and clusters.
#'
#'
#' @references Chris Fraley and Adrian E. Raftery (2002) Model-based Clustering, Discriminant Analysis and Density Estimation Journal of the American
#' Statistical Association 97:611-631
#'
#' @param maf an MAF object generated by \code{read.maf}
#' @param vafCol manually specify column name for vafs. Default looks for column 't_vaf'
#' @param tsb specify Tumor_Sample_Barcode for which clustering has to be done.
#' @param plot logical plots density curve and clusters.
#' @param top if \code{tsb} is NULL, uses top n number of most mutated samples. Defaults to 5.
#' @return list of clustering tables.
#' @export

inferHeterogeneity = function(maf, tsb = NULL, top = 5, vafCol = NULL, plot = T){

  suppressMessages(require(mclust))

  dat = maf@data

  if(!'t_vaf' %in% colnames(dat)){
    if(is.null(vafCol)){
      print(colnames(dat))
      stop('t_vaf field is missing. Use addReadCounts to add read-depth and vaf info, Or use vafCol to manually specify vaf column name.')
    }else{
      colnames(dat)[which(colnames(dat) == vafCol)] = 't_vaf'
    }
  }

  if(is.null(tsb)){
    tsb = as.character(maf$variants.per.sample[1:top,Tumor_Sample_Barcode])
  }

  #empty df to store cluster info
  clust.dat = c()

  dat.tsb = data.frame(dat[dat$Tumor_Sample_Barcode %in% tsb])
  dat.tsb = dat.tsb[,c('Hugo_Symbol', 'Tumor_Sample_Barcode','t_vaf')]

  max.vaf = max(as.numeric(dat.tsb$t_vaf[complete.cases(dat.tsb$t_vaf)]))

  if(max.vaf > 1){
    max.vaf = 100
  }else{
    max.vaf = 1
  }

  for(i in 1:length(tsb)){
    tsb.dat = dat.tsb[dat.tsb$Tumor_Sample_Barcode == tsb[i],]
    tsb.dat = tsb.dat[!is.na(tsb.dat$t_vaf),]
    #cluster
    tsb.cluster = densityMclust(tsb.dat[,"t_vaf"])
    tsb.dat$cluster = as.character(tsb.cluster$classification)

    tsb.dat.dens = ggplot(tsb.dat, aes(t_vaf))+geom_density(size = 1)+geom_point(aes(y = 0, x = t_vaf, color = cluster), size = 3, alpha = 0.6)+
      theme(legend.position = 'bottom', plot.title = element_text(size = 12))+xlab('VAF')+xlim(0,max.vaf)+ylab('')+ggtitle(tsb[i])

    #axis.text.y = element_blank(), axis.ticks.y = element_blank()

    tsb.dat.bar = ggplot(tsb.dat, aes(x = cluster, t_vaf, color = cluster))+geom_boxplot()+coord_flip()+xlab('')+ylab('')+
      theme(legend.position = 'none', axis.text = element_blank(), axis.ticks = element_blank(), axis.line = element_blank())+ylim(0,max.vaf)

    tsb.dat.gg = plot_grid(tsb.dat.bar, tsb.dat.dens, nrow = 2, ncol =  1, rel_heights = c(0.25, 1))

    clust.dat = rbind(clust.dat, tsb.dat)

    if(plot){
      print(tsb.dat.gg)
    }

  }

  clust.dat.mean = ddply(.data = clust.dat, .variables = c('Tumor_Sample_Barcode', 'cluster'),summarise,  meanVaf = mean(t_vaf))

  return(list(clusterData = clust.dat, clusterMeans = clust.dat.mean))
}
