#' draw an oncoprint similar to the cBioportal output.
#' @details takes output generated by \code{read.maf} and draw oncoprint using ggplot2.
#'
#' @param maf output generated by \code{read.maf}
#' @param genes draw oncoprint for these genes. default NULL. Plots top 5 genes.
#' @param sort logical sort oncomatrix for enhanced visualization. Defaults to True.
#' @return NULL
#' @export


oncoprint = function(maf, genes = NULL, sort = T, legend = T, annotation = NULL, removeNonMutated = F){

  mat_origin = maf$numericMatrix

  #if user doesnt provide a gene vector, use top 5.
  if(is.null(genes)){
    mat = mat_origin[1:5, ]
  } else{
    mat = mat_origin[genes,]
  }

  #remove nonmutated samples to improve visualization
  if(removeNonMutated){
    tsb = colnames(mat)
    tsb.exclude = colnames(mat[,colSums(mat) == 0])
    tsb.include = tsb[!tsb %in% tsb.exclude]
    mat = mat[,tsb.include]
  }

  #Sort
  if(sort){
    mat[mat != 0] = 1 #replacing all non-zero integers with 1 improves sorting (& grouping)
    tmat = t(mat)
    mat = t(tmat[do.call(order, c(as.list(as.data.frame(tmat)), decreasing = T)), ])
  }

  char.mat = maf$oncoMatrix
  char.mat = char.mat[rownames(mat),]
  char.mat = char.mat[,colnames(mat)]
  #final matrix for plotting
  mat = char.mat

  col = c(brewer.pal(12, name = "Paired"), brewer.pal(11, name = "Spectral")[1:3], "maroon")
  names(col) = names = c("Nonstop_Mutation", "Frame_Shift_Del",
                         "Intron", "Missense_Mutation", "IGR", "Nonsense_Mutation",
                         "RNA", "Splice_Site", "In_Frame_Del", "Frame_Shift_Ins",
                         "Silent", "In_Frame_Ins", "ITD", "In_Frame_Ins", "Translation_Start_Site",
                         "two_hit")

  tc = unique(unlist(apply(mat,1,unique)))
  tc = tc[!tc=='']

  type_col = col[tc]
  type_name = names(type_col)
  names(type_name) = type_name

  #Make annotation
  if(!is.null(annotation)){
    annotation[,1] = gsub(pattern = '-', replacement = '.', x = annotation[,1])
    rownames(annotation) = annotation[,1]
    annotation = annotation[colnames(mat_origin),]
    annotation = annotation[complete.cases(annotation),]
    anno.df = data.frame(row.names = annotation[,1])
    anno.df = cbind(anno.df, annotation[,2:ncol(annotation)])
    colnames(anno.df) = colnames(annotation)[2:ncol(annotation)]
    bot.anno = HeatmapAnnotation(anno.df)
  }

  #from oncoprint source ComplexHeatmap
  add_oncoprint = function(type, x, y, width, height) {

    for(i in 1:length(type_name)){
      if(any(type %in% type_name[i])) {
        grid.rect(x, y, width - unit(0.5, "mm"), height - unit(1, "mm"), gp = gpar(col = NA, fill = type_col[type_name[i]]))
      }
    }
    if(any(type %in% "")) {
      grid.rect(x, y, width - unit(0.5, "mm"), height - unit(1, "mm"), gp = gpar(col = NA, fill = "#CCCCCC"))
    }
  }

  if(is.null(annotation)){
    ht = Heatmap(mat, rect_gp = gpar(type = "none"), cell_fun = function(j, i, x, y, width, height, fill) {
      type = mat[i,j]
      add_oncoprint(type, x, y, width, height)
    }, row_names_gp = gpar(fontsize = 10), show_column_names = FALSE, show_heatmap_legend = FALSE,
    top_annotation_height = unit(2, "cm"))
  }else{
    ht = Heatmap(mat, rect_gp = gpar(type = "none"), cell_fun = function(j, i, x, y, width, height, fill) {
      type = mat[i,j]
      add_oncoprint(type, x, y, width, height)
    }, row_names_gp = gpar(fontsize = 10), show_column_names = FALSE, show_heatmap_legend = FALSE,
    top_annotation_height = unit(2, "cm"), bottom_annotation = bot.anno)

  }

  legend = legendGrob(labels = type_name[names(type_col)],  pch = 15, gp = gpar(col = type_col), nrow = 2)

  draw(ht, newpage = FALSE, annotation_legend_side = "bottom", annotation_legend_list = list(legend))
}
