#' draw an oncostrip similar to cBioportal oncoprinter output.
#'
#' @param maf an MAF object generated by \code{read.maf}
#' @param genes draw oncoprint for these genes. default NULL. Plots top 5 genes.
#' @param sort logical sort oncomatrix for enhanced visualization. Defaults to True.
#' @param annotation \code{data.frame} with first column containing Tumor_Sample_Barcodes and rest of columns with annotations.
#' @param top how many top genes to be drawn. defaults to 5.
#' @param removeNonMutated Logical. If \code{TRUE} removes samples with no mutations in the oncoplot for better visualization.
#' @param showTumorSampleBarcodes logical to include sample names.
#' @param colors named vector of colors for each Variant_Classification.
#' @return None.
#' @examples
#' laml.maf <- system.file("extdata", "tcga_laml.maf.gz", package = "maftools")
#' laml <- read.maf(maf = laml.maf, removeSilent = TRUE, useAll = FALSE)
#' dev.new()
#' oncostrip(maf = laml, genes = c('NPM1', 'RUNX1'), removeNonMutated = TRUE)
#'
#' @export


oncostrip = function(maf, genes = NULL, sort = TRUE, annotation = NULL, removeNonMutated = FALSE, top = 5, showTumorSampleBarcodes = FALSE, colors = NULL){

  mat_origin = maf@numericMatrix

  if(ncol(mat_origin) < 2){
    stop('Cannot create oncoplot for single sample. Minimum two sample required ! ')
  }

  if(nrow(mat_origin) <2){
    stop('Minimum two genes required !')
  }

  #if user doesnt provide a gene vector, use top 5.
  if(is.null(genes)){
    mat = mat_origin[1:top, ]
  } else{
    mat = mat_origin[genes,]
  }

  #remove nonmutated samples to improve visualization
  if(removeNonMutated){
    tsb = colnames(mat)
    tsb.exclude = colnames(mat[,colSums(mat) == 0])
    tsb.include = tsb[!tsb %in% tsb.exclude]
    mat = mat[,tsb.include]
  }

  #Sort
  if(sort){
    mat[mat != 0] = 1 #replacing all non-zero integers with 1 improves sorting (& grouping)
    tmat = t(mat)
    mat = t(tmat[do.call(order, c(as.list(as.data.frame(tmat)), decreasing = TRUE)), ])
  }

  char.mat = maf@oncoMatrix
  char.mat = char.mat[rownames(mat),]
  char.mat = char.mat[,colnames(mat)]
  #final matrix for plotting
  mat = char.mat

  if(is.null(colors)){
    col = c(brewer.pal(12,name = "Paired"),brewer.pal(11,name = "Spectral")[1:3],'black')
    names(col) = names = c('Nonstop_Mutation','Frame_Shift_Del','Silent','Missense_Mutation','IGR','Nonsense_Mutation',
                           'RNA','Splice_Site','Intron','Frame_Shift_Ins','In_Frame_Dell','In_Frame_Del','ITD','In_Frame_Ins','Translation_Start_Site',"Multi_Hit")
  }else{
    col = colors
  }


  tc = unique(unlist(apply(mat,1,unique)))
  tc = tc[!tc=='']

  type_col = col[tc]
  type_name = names(type_col)
  names(type_name) = type_name

  #Make annotation
  if(!is.null(annotation)){
    annotation[,1] = gsub(pattern = '-', replacement = '.', x = annotation[,1])

    if(nrow(annotation[duplicated(annotation$Tumor_Sample_Barcode),]) > 0){
      annotation = annotation[!duplicated(annotation$Tumor_Sample_Barcode),]
    }

    rownames(annotation) = annotation[,1]
    annotation = annotation[colnames(mat_origin),]
    annotation = annotation[complete.cases(annotation),]
    anno.df = data.frame(row.names = annotation[,1])
    anno.df = cbind(anno.df, annotation[,2:ncol(annotation)])
    colnames(anno.df) = colnames(annotation)[2:ncol(annotation)]
    bot.anno = HeatmapAnnotation(anno.df)
  }

  #from oncoprint source ComplexHeatmap
  add_oncoprint = function(type, x, y, width, height) {

    for(i in 1:length(type_name)){
      if(any(type %in% type_name[i])) {
        grid::grid.rect(x, y, width - grid::unit(0.5, "mm"), height - grid::unit(1, "mm"), gp = grid::gpar(col = NA, fill = type_col[type_name[i]]))
      }
    }
    if(any(type %in% "")) {
      grid::grid.rect(x, y, width - grid::unit(0.5, "mm"), height - grid::unit(1, "mm"), gp = grid::gpar(col = NA, fill = "#CCCCCC"))
    }
  }

  if(is.null(annotation)){
    ht = ComplexHeatmap::Heatmap(mat, rect_gp = grid::gpar(type = "none"), cell_fun = function(j, i, x, y, width, height, fill) {
      type = mat[i,j]
      add_oncoprint(type, x, y, width, height)
    }, row_names_gp = grid::gpar(fontsize = 10), show_column_names = showTumorSampleBarcodes, show_heatmap_legend = FALSE,
    top_annotation_height = grid::unit(2, "cm"))
  }else{
    ht = ComplexHeatmap::Heatmap(mat, rect_gp = grid::gpar(type = "none"), cell_fun = function(j, i, x, y, width, height, fill) {
      type = mat[i,j]
      add_oncoprint(type, x, y, width, height)
    }, row_names_gp = grid::gpar(fontsize = 10), show_column_names = showTumorSampleBarcodes, show_heatmap_legend = FALSE,
    top_annotation_height = grid::unit(2, "cm"), bottom_annotation = bot.anno)

  }

  legend = grid::legendGrob(labels = type_name[names(type_col)],  pch = 15, gp = grid::gpar(col = type_col), nrow = 2)

  draw(ht, newpage = FALSE, annotation_legend_side = "bottom", annotation_legend_list = list(legend))
}
