#' Plot APOBEC distribution of signatures.
#'
#' @description Plots distriubtion of APOBEC enriched signatures (TCW) as a radial plot
#'
#' @details Plots distriubtion of APOBEC enriched signatures (TCW) as a radial plot
#' Plot is inspired from http://weather-radials.com/ and its ggplot implmentation by Andriy Gazin (https://github.com/andriy-gazin/weather-radials)
#'
#' @param mat Input matrix of diemnsion nx96 generated by \code{\link{trinucleotideMatrix}}
#'

plotApobec = function(mat){
  apobecSigs = mat$APOBEC_scores

  apobecMat = mat$nmf_matrix[apobecSigs[APOBEC_Enriched %in% 'yes', Tumor_Sample_Barcode],]
  apobecMat = t(apply(X = apobecMat, 1, function(x) round(x = x/sum(x), digits = 4)))

  nonApobecMat = mat$nmf_matrix[rownames(mat$nmf_matrix)[!rownames(mat$nmf_matrix) %in% rownames(apobecMat)],]
  nonApobecMat = t(apply(X = nonApobecMat, 1, function(x) round(x = x/sum(x), digits = 4)))

  apobecMat = data.table::setDT(as.data.frame(apobecMat), keep.rownames = TRUE)
  apobecMat = data.table::melt(apobecMat, id.vars = 'rn')



}
