#' Plot gistic results as a bubble plot.
#' @description Plots significantly altered cytobands as a function of number samples in which it is altered and number genes it contains. Size of each bubble is according to -log10 transformed q values.
#' @param gistic an object of class \code{GISTIC} generated by \code{readGistic}
#' @param color colors for Amp and Del events.
#' @param file if given saves plot as a pdf.
#' @param width width of the file to be saved.
#' @param height height of the file to be saved.
#' @param txtSize label size for bubbles.
#' @examples
#' all.lesions <- system.file("extdata", "all_lesions.conf_99.txt", package = "maftools")
#' amp.genes <- system.file("extdata", "amp_genes.conf_99.txt", package = "maftools")
#' del.genes <- system.file("extdata", "del_genes.conf_99.txt", package = "maftools")
#' laml.gistic = readGistic(gisticAllLesionsFile = all.lesions, gisticAmpGenesFile = amp.genes, gisticDelGenesFile = del.genes, isTCGA = TRUE)
#' plotGisticResults(gistic = laml.gistic)
#' @return nothing
#' @export

plotGisticResults = function(gistic, color = NULL, file = NULL, width = 6, height = 5, txtSize = 3){
  g = getCytobandSummary(gistic)

  if(is.null(color)){
    color = c('Amp' = 'red', 'Del' = 'blue')
  }

  g$lab = sapply(strsplit(x = g$Unique_Name, split = ':'), '[', 2)

  g$pos = ifelse(test = g$Variant_Classification %in% 'Amp', yes = g$nGenes, no = -1 * g$nGenes)

  gist.gg = ggplot(data = g, aes(x = nSamples, y = pos, size = -log10(qvalues), color = Variant_Classification,
                       label = lab))+geom_point(alpha = 0.6)+xlab('nSamples')+ylab('nGenes')+
    ggrepel::geom_text_repel(size = txtSize)+cowplot::theme_cowplot(font_size = 10)+cowplot::background_grid(major = 'xy')+
    theme(legend.position = 'bottom')+scale_colour_manual(values = color, name = c('CNV', ''))

  if(!is.null(file)){
    cowplot::save_plot(filename = paste(file, 'pdf', sep='.'), plot = gist.gg, base_height = height, base_width = width)
  }else{
    print(gist.gg)
  }
}
