#' Read and summarize gistic output.
#' @description A little function to summarize gistic output files. Summarized output is returned as a list of tables.
#' @param gisticAllLesionsFile All Lesions file generated by gistic. e.g; all_lesions.conf_XX.txt, where XX is the confidence level. Default NULL.
#' @param gisticAmpGenesFile Amplification Genes file generated by gistic. e.g; amp_genes.conf_XX.txt, where XX is the confidence level. Default NULL.
#' @param gisticDelGenesFile Deletion Genes file generated by gistic. e.g; del_genes.conf_XX.txt, where XX is the confidence level. Default NULL.
#' @param isTCGA Is the data from TCGA. Default FALSE.
#' @return A list of summarized data.
#' @export
#' @examples
#' all.lesions <- system.file("extdata", "all_lesions.conf_99.txt", package = "maftools")
#' amp.genes <- system.file("extdata", "amp_genes.conf_99.txt", package = "maftools")
#' del.genes <- system.file("extdata", "del_genes.conf_99.txt", package = "maftools")
#' laml.gistic = readGistic(gisticAllLesionsFile = all.lesions, gisticAmpGenesFile = amp.genes, gisticDelGenesFile = del.genes, isTCGA = TRUE)
#' @details
#' Requires output files generated from GISTIC. Gistic documentation can be found here ftp://ftp.broadinstitute.org/pub/GISTIC2.0/GISTICDocumentation_standalone.htm

readGistic = function(gisticAllLesionsFile, gisticAmpGenesFile = NULL, gisticDelGenesFile = NULL, isTCGA = FALSE){

  message('Processing Gistic files..')

  if(is.null(gisticAmpGenesFile) & is.null(gisticDelGenesFile)){
    stop('Missing gistic genes files ! Provide atleast one of amp_genes.conf_xx.txt or del_genes.conf_xx.txt file.')
  }

  all.lesions = data.table::fread(input = gisticAllLesionsFile,stringsAsFactors = FALSE, header = TRUE)

  if(colnames(all.lesions)[ncol(all.lesions)] == paste('V', ncol(all.lesions), sep='')){
    all.lesions = all.lesions[,1:c(ncol(all.lesions)-1), with = FALSE]
  }

  all.lesions = all.lesions[!grep(pattern = 'CN values', x = all.lesions$`Unique Name`),]

  qval = all.lesions[,c(2, 6), with =FALSE]
  colnames(x = qval) = c('Cytoband', 'qvalues')

  all.lesions = all.lesions[,c(1,2,10:ncol(all.lesions)), with =FALSE]
  colnames(all.lesions) = gsub(pattern = '-', replacement = '.', x = colnames(all.lesions))

  #Only fot TCGA
  #colnames(all.lesions) = substr(x = colnames(all.lesions), start = 1, stop = 12)
  colnames(all.lesions)[c(1,2)] = c('Unique_Name', 'cytoband')
  all.lesions$Unique_Name = gsub(pattern = ' ', replacement = '_', x = all.lesions$Unique_Name)
  all.lesions$Unique_Name = gsub(pattern = '__', replacement = '_', x = all.lesions$Unique_Name)

  temp.map = all.lesions[,.(Unique_Name, cytoband)]
  temp.map$CN = substr(x = temp.map$Unique_Name, start = 1, stop = 3)

  all.lesions[,Unique_Name := NULL]

  all.lesions.melt = suppressWarnings(data.table::melt(all.lesions, id.vars = 'cytoband'))
  all.lesions.melt = all.lesions.melt[value %in% c(1, 2)]

  if(!is.null(gisticAmpGenesFile)){
    ampGenes = data.table::fread(input = gisticAmpGenesFile, stringsAsFactors = FALSE, header = TRUE)
    ampGenes = ampGenes[c(4:nrow(ampGenes)),]
    ampGenes$cytoband = gsub(pattern = ' ', replacement = '_', x = ampGenes$cytoband)

    if(colnames(ampGenes)[ncol(ampGenes)] == paste('V', ncol(ampGenes), sep='')){
      ampGenes = ampGenes[,1:c(ncol(ampGenes)-1), with = FALSE]
    }

    ampGenes = data.table::melt(ampGenes, id.vars = 'cytoband')
    ampGenes = ampGenes[!value %in% '']
    #ampGenes$value = sapply(strsplit(x = ampGenes$value, split = '|', fixed = TRUE), '[', 1)
    ampGenes = ampGenes[!grep(pattern = '|', x = ampGenes$value, fixed = TRUE)]
    ampGenes = ampGenes[,.(variable, value)]
  }

  if(!is.null(gisticDelGenesFile)){
    delGenes = data.table::fread(input = gisticDelGenesFile, stringsAsFactors = FALSE, header = TRUE)
    delGenes = delGenes[c(4:nrow(delGenes)),]
    delGenes$cytoband = gsub(pattern = ' ', replacement = '_', x = delGenes$cytoband)

    if(colnames(delGenes)[ncol(delGenes)] == paste('V', ncol(delGenes), sep='')){
      delGenes = delGenes[,1:c(ncol(delGenes)-1), with = FALSE]
    }

    delGenes = suppressWarnings(data.table::melt(delGenes, id.vars = 'cytoband'))
    delGenes = delGenes[!value %in% '']
    #delGenes$value = sapply(strsplit(x = delGenes$value, split = '|', fixed = TRUE), '[', 1)
    delGenes = delGenes[!grep(pattern = '|', x = delGenes$value, fixed = TRUE)]
    delGenes = delGenes[,.(variable, value)]
  }

  if(exists('ampGenes') & exists('delGenes')){
    cnGenes = rbind(ampGenes, delGenes)
  } else if(exists('ampGenes')){
    cnGenes = ampGenes
  } else if(exists('delGenes')){
    cnGenes = delGenes
  }

  cnSamples = unique(x = as.character(all.lesions.melt$variable))
  cnDT = c()

  for(i in 1:length(cnSamples)){
    cytBands = all.lesions.melt[variable %in% cnSamples[i], cytoband]
    cytBandsGenes = cnGenes[variable %in% cytBands]
    cytBandsGenes[,TumorSampleBarcode := cnSamples[i]]
    cnDT = rbind(cnDT, cytBandsGenes)
  }

  cnDT$CN = suppressWarnings(as.character(factor(x = cnDT$variable, levels = temp.map$cytoband, labels = temp.map$CN)))
  colnames(cnDT) = c('Cytoband', 'Hugo_Symbol', 'Tumor_Sample_Barcode', 'Variant_Classification')

  if(isTCGA){
    cnDT$Tumor_Sample_Barcode = substr(x = cnDT$Tumor_Sample_Barcode, start = 1, stop = 12)
  }

  cnDT = suppressWarnings(cnDT[,Variant_Type := 'CNV'])
  cnDt.summary = summarizeGistic(gistic = cnDT)
  cnDt.mat = gisticMap(gistic = cnDT)

  cnDt.summary$cytoband.summary = merge(cnDt.summary$cytoband.summary, qval, by = 'Cytoband', all.x = TRUE)

  g = GISTIC(data = cnDT, cnv.summary = cnDt.summary$cnv.summary,
             cytoband.summary = cnDt.summary$cytoband.summary,
          gene.summary = cnDt.summary$gene.summary,
          cnMatrix = cnDt.mat$oncomat, numericMatrix = cnDt.mat$nummat,
          classCode = cnDt.mat$vc, summary = cnDt.summary$summary)

  return(g)
}
