#' Classifies SNPs into transitions and transversions
#' @description takes output generated by read.maf and classifies Single Nucleotide Variants into Transitions and Transversions.
#'
#' @param maf an MAF object generated by \code{\link{read.maf}}
#' @param useSyn Logical. Whether to include synonymous variants in analysis. Defaults to FALSE.
#' @param plot plots a titv fractions. default TRUE.
#' @return list of \code{data.frame}s with Transitions and Transversions summary.
#' @export


titv = function(maf, useSyn = F, plot = T)
{

  #Synonymous variants
  maf.silent = maf@maf.silent
  #Main data
  maf = maf@data

  #in case user read maf without removing silent variants, remove theme here.
  silent = c("Silent", "Intron", "RNA", "3'UTR", "3'Flank", "5'UTR", "5'Flank", "IGR")
  maf = maf[!Variant_Classification %in% silent] #Remove silent variants from main table

  if(useSyn){
    maf = rbind(maf, maf.silent, fill = T)
  }

  maf = maf[Variant_Type == 'SNP']

  #Some TCGA studies have Start_Position set to as 'position'. Change if so.
  if(length(grep(pattern = 'Start_position', x = colnames(maf))) > 0){
    colnames(maf)[which(colnames(maf) == 'Start_position')] = 'Start_Position'
  }

  if(length(grep(pattern = 'End_position', x = colnames(maf))) > 0){
    colnames(maf)[which(colnames(maf) == 'End_position')] = 'End_Position'
  }

  maf = maf[,.(Hugo_Symbol, Start_Position, End_Position, Reference_Allele, Tumor_Seq_Allele2, Tumor_Sample_Barcode)]
  maf$Tumor_Sample_Barcode = as.factor(as.character(maf$Tumor_Sample_Barcode))
  class.summary = c()
  class.summary.df = c()
  TiTv.fractions = data.frame()
  mut.raw.counts = data.frame(row.names = c("A-G", "T-C", "C-T", "G-A", "A-T", "T-A", "A-C", "T-G", "C-A", "G-T", "C-G", "G-C"))

  tsbs = levels(maf[,Tumor_Sample_Barcode])

  for (i in 1:length(tsbs)) {
    mut = data.frame(maf[Tumor_Sample_Barcode == tsbs[i]])

    mut$con = paste(mut[, 4], mut[, 5], sep = "-")
    mut$con = as.factor(mut$con)
    mut$con = factor(mut$con, levels = c("A-G", "T-C", "C-T",
                                         "G-A", "A-T", "T-A", "A-C", "T-G", "C-A", "G-T",
                                         "C-G", "G-C"))
    mut.df = data.frame(absolute_counts = summary(mut$con))
    mut.raw.counts = cbind(mut.raw.counts, mut.df)
    colnames(mut.raw.counts)[ncol(mut.raw.counts)] = tsbs[i]
    mut.df$class = rep(rownames(mut.df)[seq(1, 12, by = 2)],each = 2)
    mut.df$TiTv = c(rep(x = "Ti", 4), rep("Tv", 8))
    mut.df$percent_contribution = mut.df$absolute_counts/sum(mut.df$absolute_counts) * 100
    mut.df$conversion = row.names(mut.df)
    mut.df = mut.df[, c(5, 1:4)]
    mut.summarized = ddply(.data = mut.df, .variables = ~class, summarise, sum(percent_contribution))
    colnames(mut.summarized) = c("class", "percent_contribution")
    mut.summarized2 = ddply(.data = mut.df, .variables = ~TiTv,
                            summarise, sum(percent_contribution))
    colnames(mut.summarized2) = c("TiTv", "percent_contribution")
    TiTv.fractions = rbind(TiTv.fractions, mut.summarized2$percent_contribution)
    rownames(TiTv.fractions)[i] = tsbs[i]
    mut.summary = list(mut.df, mut.summarized, mut.summarized2)
    class.summary.df = rbind(class.summary.df, c(mut.summary[[2]][,2], tsbs[i]))
    class.summary = rbind(class.summary, cbind(mut.summary[[2]],
                                               pid = tsbs[i]))
  }
  #add titv classification
  class.summary$TiTv = suppressWarnings( as.character(factor(x = class.summary$class, levels = mut.df$class, labels = mut.df$TiTv)) )
  colnames(TiTv.fractions) = c("Ti", "Tv")

  class.summary.df = as.data.frame(class.summary.df[, c(7, 1:6)])
  colnames(class.summary.df) = c("Tumor_Sample_Barcode", mut.summary[[2]][,1])
  class.summary.df[,2:7] = apply(class.summary.df[,2:7], 2, as.numeric)
  titv.res = list(fraction.contribution = class.summary.df, raw.counts = mut.raw.counts, TiTv.fractions = TiTv.fractions)

  if(plot){
    plotTiTv(res = titv.res)
  }

  return(titv.res)

}
